'use strict';

import os from 'os';

export const HEADER = `// @flow
/* This file is automatically generated by css-modules-flow-types */`;

export const flow = (tokensArray, indent = '  ') => {
  const props = tokensArray
    .sort()
    .map(key => `${indent}+'${key}': string;`)
    .join(os.EOL);

  return `${HEADER}
declare module.exports: {|
${props}
|};
`;
};

export const reason = (filename, tokens, indent = '  ') => {
  const props = tokens
    .sort()
    .map(key => `${indent}'${key}': string`)
    .join(`,${os.EOL}`);

  return `[@bs.module] external style : Js.t({
${props}
}) = "./${filename}";
`;
};
